name: Deploy to EC2 on Push

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Portfolio
            git pull origin main
            sudo docker build -t portfolio-app .
            sudo docker stop portfolio || true && sudo docker rm portfolio || true
            sudo docker run -d --name portfolio -p 80:80 portfolio-app
